name: .NET Core 

on:
  push:
    branches:
    - main
    - v[0-9]+.[0-9]+

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - name: Setup Graphviz
      uses: ts-graphviz/setup-graphviz@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100-preview.1.21103.13
    - uses: dotnet/nbgv@master
      id: nbgv
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --configuration Release --no-build
    - name: Pack
      run: dotnet pack --no-build --configuration Release
#    - name: Push Package
#      run: dotnet nuget push artifacts/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://nuget.org
#    - name: Push Symbols Package
#      run: dotnet nuget push artifacts/*.snupkg -k ${{ secrets.NUGET_API_KEY }} -s https://nuget.org
